### PR TITLE
More diagnostic info on the large number modulo tests on 32-bit systems

### PR DESCRIPTION
**Pull request by zmughal**

### CODE REVIEW

**Comment by mohawk2** [comment]
Could we also diag the `$INT_MAX` too?

**Comment by mohawk2** [comment]
(done with a sprintf into hex?)

**Comment by zmughal** [comment]
Done!

**Comment by mohawk2** [comment]
This looks good to me. If Travis (after my rebase/force-push just now) approves, we should merge this.

**Comment by mohawk2** [comment]
My rebase needed me to edit this slightly because @devel-chm has already TODO-ed the relevant tests. Your updates are still useful.

**Pull request merged**
