### PR TITLE
403 fix

### PR DESCRIPTION
**Pull request by drzowie**
fixes bug 403

### CODE REVIEW

**Comment by zmughal** [comment]
If you try to push to the master on GitHub to close the PR, it will be reverted automatically. You have to push to the branch on SourceForge. This is a "feature" of @wchristian sync script.

Also, do not do a merge before the CI jobs are finished, otherwise they will fail because it will not know where to pull from. :-)

**Comment by zmughal** [comment]
I am going to rebuild the last commit on the CI.

**Comment by zmughal** [comment]
This has passed on all CI systems. Going to merge it in.

**Comment by devel-chm** [comment]
If the topic branch has been merged into master, can it be deleted now?  Hard to track what is in the sf.net repo with dangling branches.  :-)

**Comment by zmughal** [comment]
Aye, I shall do that now.

**Pull request merged**
