### PR TITLE
Add tests for mixed PDL::Complex binop cdouble operations

### PR DESCRIPTION
**Pull request by wlmb**
Added a few (TODO) tests for the type and value of PDL::Complex + and  * cdouble

### CODE REVIEW

**Comment by mohawk2** [comment]
I've just rebased and force-pushed this, catching up with over 740(!) commits on `master`.

**Comment by mohawk2** [comment]
@wlmb Again, thank you for making these! Since then, my thinking is that PDL::Complex is best not disturbed further, given that users can explicitly use `PDL::Complex->from_native` and `$pdlc->as_native` to go backwards and forwards explicitly. Given the horrors of the extra dimension, my feeling is that is much, much better than hiding the difference.

What do you think? If you agree, we can close this PR.

**Comment by wlmb** [comment]
> 
> What do you think? If you agree, we can close this PR.

I guess we can.

**Comment by mohawk2** [comment]
Thank you!

**Pull request closed without merging**
