### PR TITLE
Assgn badflag propagation

### PR DESCRIPTION
**Pull request by hainest**
Add propagation of badflag with .= (Ops::assgn) for sf.net bug 3543056.

I tried to make the documentation as explicit as I could that badflags are *not* automatically propagated to the parent of a subpiddle, and pointed to the relevant sections of PDL::Bad docs.

Many thanks.

Tim

### CODE REVIEW

**Comment by zmughal** [comment]
Is this PR still valid?

**Comment by mohawk2** [comment]
Not as it stands - look at all those "merge" instead of rebasing!

**Comment by mohawk2** [comment]
Obsoleted by the passage of time, and #51.

**Comment by hainest** [comment]
Terribly sorry. I had completely forgotten about this. Thanks for chasing it down!

**Comment by mohawk2** [comment]
Nothing to apologise for! Are you comfortable these days with rebasing? Are there other contributions you'd like to make to PDL?

**Pull request closed without merging**
