### PR TITLE
fix #201

### LINKED ISSUE #201: build fail with perl 5.14
Hi,
on a pristine 5.14 environment I get this build failure:

$ cpanm -v -n PDL

`Running Mkbootstrap for Core ()
chmod 644 "Core.bs"
"/home/simon/.plenv/versions/5.14.4/bin/perl5.14.4" -MExtUtils::Command::MM -e 'cp_nonempty' -- Core.bs ../../blib/arch/auto/PDL/Core/Core.bs 644
"/home/simon/.plenv/versions/5.14.4/bin/perl5.14.4" "/home/simon/.plenv/versions/5.14.4/lib/perl5/5.14.4/ExtUtils/xsubpp"  -typemap '/home/simon/.plenv/versions/5.14.4/lib/perl5/5.14.4/ExtUtils/typemap' -typemap '/home/simon/.cpanm/work/1479896084.7128/PDL-2.017/Basic/Core/typemap'  Core.xs > Core.xsc
Undefined subroutine &ExtUtils::ParseXS::errors called at /home/simon/.plenv/versions/5.14.4/lib/perl5/5.14.4/ExtUtils/xsubpp line 41.
Makefile:380: recipe for target 'Core.c' failed
make[2]: *** [Core.c] Error 255
make[2]: Leaving directory '/home/simon/.cpanm/work/1479896084.7128/PDL-2.017/Basic/Core'
Makefile:515: recipe for target 'subdirs' failed
make[1]: *** [subdirs] Error 2
make[1]: Leaving directory '/home/simon/.cpanm/work/1479896084.7128/PDL-2.017/Basic'
Makefile:538: recipe for target 'subdirs' failed
make: *** [subdirs] Error 2
! Installing PDL failed. See /home/simon/.cpanm/work/1479896084.7128/build.log for details. Retry with --force to force install it.
FAIL
1 distribution installed
`
The whole build log is here: http://pastebin.ca/3741536

When repeating the cpanm command, it succeeds. When I then uninstall PDL and ExtUtils::ParseXS and repeat the install it fails again.

OS is Linux.

Cheers, Simon

### PR DESCRIPTION
**Pull request by amba**

### CODE REVIEW

**Comment by mohawk2** [comment]
Thanks for this! Please could you:

* make the whitespace be consistent with the surrounding text (spaces not tabs)
* help me understand how this is needed for <=5.14, when there is a build done for 5.10
* help me understand why you're adding the `EU::PXS` version to `CONFIGURE_REQUIRES` since as far as I know that's simply incorrect; the configure (building `Makefile.PL`) does not as far as I know need EU::PXS, but the build does
* if I'm right on the above, not delete from the `BUILD_REQUIRES`

**Comment by mohawk2** [comment]
To add to my last: #201 explains why I now agree re the second and third points. However, please could you execute the 1st and 4th points? :-) @amba

**Comment by amba** [comment]
@mohawk2, Thanks for the quick reply!

The indentation is fixed now.

Why should we duplicate the E::P requirement in BUILD_REQUIRES? From [CPAN::Meta::Spec#Phases](https://metacpan.org/pod/CPAN::Meta::Spec#Phases) it seems that config requirements automatically apply to the build phase also.

**Comment by mohawk2** [comment]
I think I experienced an issue with that in `Gimp`. However, I'm (very) pleased to be wrong. Seems like all my issues were either answered or wrong, and this is now good to go.

@devel-chm if you agree, want to merge? @amba If you feel that this would fix #201, want to use a fancy GH feature and edit either the PR title or opening comment to say "fix #201"?

**Comment by devel-chm** [comment]
I can't figure out how to get the fix from github to apply to the sf.net repo.  Is there a way to get the change as a patch that could be applied to sf.net pdl master?

**Comment by mohawk2** [comment]
That's a good question. If you look on the "Merge pull request" section of this page, you'll see a link to "view command line instructions". The title is "Merging via command line", and the commands I believe you'll want are:

```
git checkout -b amba-fix-5.14 master # make a local branch
git pull git://github.com/amba/pdl.git fix-5.14 # pull from the right branch of @amba's repo onto that local branch
git checkout master # back to your local master
git merge --no-ff amba-fix-5.14 # merge his branch onto your master
git push origin master # you might need to change "origin" to the remote you have for SF
```

**Comment by amba** [comment]
Shell I provide a patch also? @mohawk2   @devel-chm

**Comment by mohawk2** [comment]
@amba That shouldn't be necessary. @devel-chm any problems with the ideas above?

**Comment by devel-chm** [comment]
The last time I tried to rebase the fix to the lastest master there were a number of merge conflicts which I haven't had time to look at or to figure out if I was doing something wrong.  I should have some more time no later than this weekend.  Of course with a ff-only compliant patch this would be done in a jiffy.

**Comment by wchristian** [comment]
I have no idea what conflicts you could possibly run into, as amba's commit already *is* fully ff-only compliant.

image

**Comment by devel-chm** [comment]
Thanks for the pointers.  I got confused with which master was which...

**Comment by devel-chm** [comment]
appveyor build is failing for strawberry perl.

**Comment by wchristian** [comment]
That looks to be an issue unrelated to this one, as it's some kind of tool for installing strawberry that's failing because of missing checksums.

**Pull request merged**
