### PR TITLE
Use container CI

### PR DESCRIPTION
**Pull request by mohawk2**

### CODE REVIEW

**Comment by zmughal** [comment]
Looking good! And it seems to run each build about 25% faster individually.

So pgplot5 needs to be added to the whitelist at <https://github.com/travis-ci/apt-package-whitelist>?

**Comment by mohawk2** [comment]
Yes it does. In the meantime, I'm going to have it built and installed per the migration instructions.

**Comment by zmughal** [comment]
OK, made a request for pgplot5 at <https://github.com/travis-ci/apt-package-whitelist/issues/759>. Do we want the others?

**Comment by mohawk2** [comment]
@zmughal I'd say yes we do.

**Comment by zmughal** [comment]
OK, I linked back from the rest of the deps here:

- [libxpm-dev](https://github.com/travis-ci/apt-package-whitelist/issues/761)
- [libvpx-dev](https://github.com/travis-ci/apt-package-whitelist/issues/760)
- [pgplot5](https://github.com/travis-ci/apt-package-whitelist/issues/759)

**Comment by mohawk2** [comment]
Great!

**Comment by zmughal** [comment]
Wow, that was quite a bit of work on pgplot5! It's looking good.

I totally agree that we should drop testing Perl v5.12 - v5.18. Those aren't that useful at this point.

**Merge**: *Aye*

**Comment by zmughal** [comment]
This will need rebasing now that the cherry-pick in <https://github.com/PDLPorters/pdl/issues/136> is on the master branch.

**Comment by mohawk2** [comment]
Rebased.

**Comment by zmughal** [comment]
@mohawk2, the whitelists for Travis-CI that we requested just went through, so shouldn't be too much work to get this working now!

**Comment by zmughal** [comment]
CI happiness all around! Looks good. Merge away!

**Merge**: *Aye*

**Pull request merged**
