### PR TITLE
test comparisons between scalars and 0-dim PDLs with badflag == 1

### PR DESCRIPTION
**Pull request by zmughal**
This is to elucidate the issues with stat() and per-PDL badvalues
brought up by Marek Gierliński in SF#390
<http://sourceforge.net/p/pdl/bugs/390/>,
<https://github.com/PDLPorters/pdl/issues/124>.

### CODE REVIEW

**Comment by zmughal** [comment]
Thread on pdl-devel <http://thread.gmane.org/gmane.comp.lang.perl.pdl.general/8729/focus=6584>

**Comment by zmughal** [comment]
Plan for further work is discussed at <http://irclog.perlgeek.de/pdl/2015-07-18#i_10918794>:

  - create a warning for when a comparison op has *_badval ∈ {0, 1} ⇒ merge to master & do a full release
  - change the output type for comparisons to byte ⇒ test on devel branch, see what breaks, & do a dev release

**Comment by zmughal** [comment]
Plan for further work is discussed at <http://irclog.perlgeek.de/pdl/2015-07-18#i_10918794>:

  - create a warning for when a comparison op has *_badval ∈ {0, 1} ⇒ merge to master & do a full release
  - change the output type for comparisons to byte ⇒ test on devel branch, see what breaks, & do a dev release

**Comment by mohawk2** [comment]
Why not just unconditionally `delete $extra{Exception};` (lines 92-6 of ops.pd)? Similarly, lines 248-54.

I'm also keen to squash together / eliminate failing commits, to ease future bisecting.

The bit of primitive.pd you changed looks like it's crying out for a bit of data-driven action.

**Comment by zmughal** [comment]
I squashed and reordered the commits.

I want to hold off on the two things you mentioned:
  - turning the badvalue propagation section in `statsover()` into a loop that applies the same to each return value: this would not give that much reduction in complexity. Not enough to justify having a a `for`/`map` to generate code.
  - removing the `Exception` key in `ops.pd`: the `Exception` is actually a placeholder for more sane ops...it is just that it was never implemented properly. There's a bug there and I'd rather leave it in for now as a `grep`pable reminder.

**Pull request merged**
