### PR TITLE
Add propagation of badflag with .= (Ops::assgn) for sf.net bug 3543056.

### PR DESCRIPTION
**Pull request by mohawk2**
Rebased version of #2. Passes tests.

### CODE REVIEW

**Comment by zmughal** [comment]
I believe this needs to only run when `WITH_BADVAL=1`. I don't think the test does so yet.

**Comment by mohawk2** [comment]
We'll be able to tell more easily once #18 is merged and we rebase against it.

**Comment by mohawk2** [comment]
Temporary close because Travis fouls up with race condition when both branch and PR.

**Comment by mohawk2** [comment]
Temporary close because Travis fouls up with race condition when both branch and PR.

**Comment by zmughal** [comment]
LIke I was saying in IRC <http://irclog.perlgeek.de/pdl/2015-03-03#i_10215431>, this won't fix the code until the `badflag` does not need to be set. Turning into TODO tests for now.

**Comment by mohawk2** [comment]
@hainest, what are your thoughts on the readiness state of this? Does work remain to be done?

**Comment by hainest** [comment]
I think that as long as folks are content with the lack of child->parent bad flag propagation, then this can be pulled into master. The (admittedly verbose) idiom for ensuring bad flag propagation is provided in the comments of assign.

**Comment by mohawk2** [comment]
I think merging should wait until post 2.008, which is imminent. However, there is talk of a much faster release, so that'll help.

May I suggest changing the location of telling people the correct idiom move from comments, to actual documentation? Feel like making a PR onto this branch? I'll then bring it across and we can see how it plays.

**Comment by hainest** [comment]
>May I suggest changing the location of telling people the correct idiom move from comments, to actual documentation?

I misspoke. The description is in the Doc field, so it should be rendered to the documentation automatically.

>Feel like making a PR onto this branch?

I thought it was already pulled. Github says that I can merge the PR, but I'm not sure how that aligns with the rebase procedure.

**Comment by mohawk2** [comment]
It means this branch, as rebased by me, *can* be merged. It doesn't mean you can do so, until you get a commit bit on the appropriate repo (of which this is a mirror). If you make your fork be up to date with this repo, then branch off this branch, then PR onto this branch (or against master, I'll figure it out), then you can submit changes to your code here. That is what I am saying you could do, if you feel it useful.

**Comment by mohawk2** [comment]
Rebased to update for `t/ops.t` change.

**Comment by mohawk2** [comment]
@hainest @d-lamb @devel-chm @zmughal @drzowie Is this ready for primetime? :-)

**Comment by hainest** [comment]
@mohawk2 I think so. I would reiterate my previous comment:

> I think that as long as folks are content with the lack of child->parent bad flag propagation, then this can be pulled into master. The (admittedly verbose) idiom for ensuring bad flag propagation is provided in the doc for `assign`.

**Comment by mohawk2** [comment]
Limitations are documented. Tests are passing. Merging.

**Comment by mohawk2** [comment]
The above-linked commit actually now means `assgn` does not need the `badflag` set on its output ndarray, which is nice to finally achieve.

**Pull request merged**
